// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn9MU6TYfLA3uAtSL41i6n0s5m7wom3vQ',
    appId: '1:969261294250:web:84b2f483ed4ab02aac66d3',
    messagingSenderId: '969261294250',
    projectId: 'hotel-app-a498d',
    authDomain: 'hotel-app-a498d.firebaseapp.com',
    storageBucket: 'hotel-app-a498d.firebasestorage.app',
    measurementId: 'G-XF1VF4J7SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0610qeOyeX1xkS4E922ApQfer8POavm8',
    appId: '1:969261294250:android:41e55f3fa32297cfac66d3',
    messagingSenderId: '969261294250',
    projectId: 'hotel-app-a498d',
    storageBucket: 'hotel-app-a498d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE9x8-KKjVN_7rBwWe0WRHWvoBjbjTWLc',
    appId: '1:969261294250:ios:7b36c8f58bb2ec21ac66d3',
    messagingSenderId: '969261294250',
    projectId: 'hotel-app-a498d',
    storageBucket: 'hotel-app-a498d.firebasestorage.app',
    iosBundleId: 'com.example.hotelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE9x8-KKjVN_7rBwWe0WRHWvoBjbjTWLc',
    appId: '1:969261294250:ios:7b36c8f58bb2ec21ac66d3',
    messagingSenderId: '969261294250',
    projectId: 'hotel-app-a498d',
    storageBucket: 'hotel-app-a498d.firebasestorage.app',
    iosBundleId: 'com.example.hotelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn9MU6TYfLA3uAtSL41i6n0s5m7wom3vQ',
    appId: '1:969261294250:web:af191a6fdf80c41bac66d3',
    messagingSenderId: '969261294250',
    projectId: 'hotel-app-a498d',
    authDomain: 'hotel-app-a498d.firebaseapp.com',
    storageBucket: 'hotel-app-a498d.firebasestorage.app',
    measurementId: 'G-H24FZJ77KP',
  );
}